In [6]:
import os
import pandas as pd
import numpy as  np
import librosa
from librosa import feature

In [15]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
fn_list_i = [
 feature.chroma_stft,
 feature.spectral_centroid,
 feature.spectral_bandwidth,
 feature.spectral_rolloff
]
 
fn_list_ii = [
 feature.rms,
 feature.zero_crossing_rate
]

def get_feature_vector(y,sr): 
   feat_vect_i = [ np.mean(funct(y=y, sr=sr)) for funct in fn_list_i]
   feat_vect_ii = [ np.mean(funct(y=y)) for funct in fn_list_ii] 
   feature_vector = feat_vect_i + feat_vect_ii 
   return feature_vector

In [55]:
df = pd.DataFrame()

In [56]:
df

Empty DataFrame
Columns: []
Index: []

In [57]:
for each_actor in os.listdir('dataset/'):
    for each_file in os.listdir(os.path.join('dataset', each_actor)):
        
        emotion = each_file.split("-")[2]
        
        if emotion == '05':
            y , sr = librosa.load(os.path.join('dataset', each_actor, each_file), sr=None)
            feature_vector = get_feature_vector(y, sr)
            df = df.append([feature_vector + ['Anger']])
        elif emotion == '04':
            y , sr = librosa.load(os.path.join('dataset', each_actor, each_file), sr=None)
            feature_vector = get_feature_vector(y, sr)
            df = df.append([feature_vector + ['Sad']])
        else:
            continue

In [58]:
df.columns = ['chrome_stft', 'spectral_centroid', 'spectral_bandwidth', 'spectral_rolloff', 'rms', 'zero_crossing_rate', 'Emotion']
df

,chrome_stft,spectral_centroid,spectral_bandwidth,spectral_rolloff,rms,zero_crossing_rate,Emotion
0,0.573611,6355.887484,5234.605322,11777.799479,0.002030,0.039407,Sad
0,0.582330,6610.435403,5502.210857,12477.565299,0.001901,0.042950,Sad
0,0.599464,6739.503744,5073.448861,11920.925152,0.001695,0.029217,Sad
0,0.600793,7106.008406,5436.401320,12793.611551,0.002221,0.040750,Sad
0,0.592469,6343.886846,5318.847928,11843.159139,0.002799,0.044057,Sad
...,...,...,...,...,...,...,...
0,0.427414,5044.967425,4783.601880,9962.539557,0.016647,0.095877,Anger
0,0.384375,4605.335977,4068.533874,8769.969512,0.029466,0.076286,Anger
0,0.382802,4657.776492,3919.602682,8551.143293,0.022338,0.069958,Anger
0,0.479681,6028.449512,4751.686295,10894.730548,0.016544,0.083097,Anger
0,0.403176,4855.821970,4140.850562,9093.407490,0.018608,0.086302,Anger

In [59]:
df.to_csv("sad_anger_emotions.csv")